server:
  servlet:
    context-path: /bcnc-test

logging:
  level:
    com.bcnc.test.infrastructure.*: INFO
    com.bcnc.test.infrastructure.api.*: DEBUG

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
  jpa:
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
  sql:
    init:
      mode: always
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    # It must be disabled on production environments
    enabled: true